### ISSUE TITLE
How to use with nextjs?

### ISSUE THREAD

**Issue by hoang-rio** [produck/svg-captcha#41]
When run in nextjs production mode. I got error.

```
Error: ENOENT: no such file or directory, open '/fonts/Comismsh.ttf'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.loadSync (/app/.next/serverless/pages/api/user/captcha.js:15277:21)
    at Object.<anonymous> (/app/.next/serverless/pages/api/user/captcha.js:2135:23)
    at Object.6HnN (/app/.next/serverless/pages/api/user/captcha.js:2162:30)
    at __webpack_require__ (/app/.next/serverless/pages/api/user/captcha.js:23:31)
    at Object./RNt (/app/.next/serverless/pages/api/user/captcha.js:344:14)
    at __webpack_require__ (/app/.next/serverless/pages/api/user/captcha.js:23:31)
    at Object.UTAq (/app/.next/serverless/pages/api/user/captcha.js:41692:16)
    at __webpack_require__ (/app/.next/serverless/pages/api/user/captcha.js:23:31)
    at Object.ctv8 (/app/.next/serverless/pages/api/user/captcha.js:42800:18)
    at __webpack_require__ (/app/.next/serverless/pages/api/user/captcha.js:23:31)
    at Object.<anonymous> (/app/.next/serverless/pages/api/user/captcha.js:1331:20)
    at Object.2g5n (/app/.next/serverless/pages/api/user/captcha.js:1347:30)
    at __webpack_require__ (/app/.next/serverless/pages/api/user/captcha.js:23:31)
    at Object.ONz8 (/app/.next/serverless/pages/api/user/captcha.js:39493:30)
    at __webpack_require__ (/app/.next/serverless/pages/api/user/captcha.js:23:31)
    at Module.f2QB (/app/.next/serverless/pages/api/user/captcha.js:43242:75)
    at __webpack_require__ (/app/.next/serverless/pages/api/user/captcha.js:23:31)
    at Module.module.exports.o2LP.__webpack_exports__.default (/app/.next/serverless/pages/api/user/captcha.js:48383:26)
    at Server.handleApiRequest (/app/node_modules/next/dist/next-server/server/next-server.js:248:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:195:21)
    at async Server.run (/app/node_modules/next/dist/next-server/server/next-server.js:298:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/fonts/Comismsh.ttf'
}
```
I reported an issue in:
https://github.com/tormozz48/algebraic-captcha/issues/16

**Comment by svengau** [comment]
hi @hoang-rio, I've got the same problem with webpack. How did you solve this issue ?

**Comment by svengau** [comment]
Hello @steambap, 

I've attached a PR to fix a small issue we can meet when using webpack: the lib crashes if the font file Comismsh.ttf doesn't exist. With this PR, the font is not loaded when the file doesn't exists, allowing the user to load it manually using the method loadFont.

Please could you review / merge ? thanks

Thanks & Regards

**Comment by hoang-rio** [comment]
> hi @hoang-rio, I've got the same problem with webpack. How did you solve this issue ?

I use nextjs server target instead of serverless target and it gone

**Comment by ujangpudin04** [comment]
can you tell me example code ?

**Comment by 0-don** [comment]
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.externals.push("svg-captcha");
    }

    return config;
  },
};
```

**Comment by jimages** [comment]
you can now add `svg-captcha` to your `next.config.mjs`

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  serverExternalPackages: ['svg-captcha'], // add svg-captcha to serverExternalPackages
}
 
module.exports = nextConfig

```
